# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Player_data": "01_summarise_rpl.ipynb",
         "Replay_data": "01_summarise_rpl.ipynb",
         "get_players": "01_summarise_rpl.ipynb",
         "get_replay_info": "01_summarise_rpl.ipynb",
         "INTERVALS_BASE": "02_handle_tracker_events.ipynb",
         "calc_realtime_index": "02_handle_tracker_events.ipynb",
         "get_pstatse": "03_macro_econ_parser.ipynb",
         "complete_pstatse_df": "03_macro_econ_parser.ipynb",
         "gen_interval_sub_dfs": "03_macro_econ_parser.ipynb",
         "get_subdf_mean": "03_macro_econ_parser.ipynb",
         "get_subdf_total": "03_macro_econ_parser.ipynb",
         "get_cappedTime": "03_macro_econ_parser.ipynb",
         "calculate_spending_coeficient": "03_macro_econ_parser.ipynb",
         "list_attr_interval_values": "03_macro_econ_parser.ipynb",
         "get_player_macro_econ_df": "03_macro_econ_parser.ipynb",
         "get_player_macro_econ_stats": "03_macro_econ_parser.ipynb",
         "data_path": "05_handle_game_events.ipynb",
         "composition_df": "04_build_parser.ipynb",
         "count_active_units": "04_build_parser.ipynb",
         "complete_count": "04_build_parser.ipynb",
         "count_composicion": "04_build_parser.ipynb",
         "count_started": "04_build_parser.ipynb",
         "get_expansion_time": "04_build_parser.ipynb",
         "list_player_upgrades": "04_build_parser.ipynb"}

modules = ["summarise_rpl.py",
           "handle_tracker_event.py",
           "macro_econ_parser.py",
           "build_parser.py",
           "handle_game_events.py"]

doc_url = "https://HDavidEspinosa.github.io/sc_training/"

git_url = "https://github.com/HDavidEspinosa/sc_training/tree/master/"

def custom_doc_links(name): return None
