# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Player_data": "00_summarise_rpl.ipynb",
         "Replay_data": "00_summarise_rpl.ipynb",
         "get_players": "00_summarise_rpl.ipynb",
         "get_replay_info": "00_summarise_rpl.ipynb",
         "INTERVALS_BASE": "01_handle_tracker_events.ipynb",
         "calc_realtime_index": "01_handle_tracker_events.ipynb",
         "get_pstatse": "02_macro_econ_parser.ipynb",
         "complete_pstatse_df": "02_macro_econ_parser.ipynb",
         "gen_interval_sub_dfs": "02_macro_econ_parser.ipynb",
         "get_subdf_mean": "02_macro_econ_parser.ipynb",
         "get_subdf_total": "02_macro_econ_parser.ipynb",
         "get_cappedTime": "02_macro_econ_parser.ipynb",
         "calculate_spending_coeficient": "02_macro_econ_parser.ipynb",
         "list_attr_interval_values": "02_macro_econ_parser.ipynb",
         "get_player_macro_econ_df": "02_macro_econ_parser.ipynb",
         "get_player_macro_econ_stats": "02_macro_econ_parser.ipynb",
         "data_path": "03_build_parser.ipynb",
         "composition_df": "03_build_parser.ipynb",
         "count_active_units": "03_build_parser.ipynb",
         "complete_count": "03_build_parser.ipynb",
         "count_composicion": "03_build_parser.ipynb",
         "count_started": "03_build_parser.ipynb",
         "list_player_upgrades": "03_build_parser.ipynb"}

modules = ["summarise_rpl.py",
           "handle_tracker_event.py",
           "macro_econ_parser.py",
           "build_parser.py"]

doc_url = "https://HDavidEspinosa.github.io/sc_training/"

git_url = "https://github.com/HDavidEspinosa/sc_training/tree/master/"

def custom_doc_links(name): return None
