# AUTOGENERATED! DO NOT EDIT! File to edit: 06_control_group_parser.ipynb (unless otherwise specified).

__all__ = ['CtrlGrpPlugin']

# Internal Cell
# Load Module's dependencies
from pathlib import Path
from pprint import pprint
from typing import *

import json
import pandas as pd
import fastcore.test as ft

# Internal Cell
import sc2reader

from .handle_tracker_event import *
from .macro_econ_parser import *

# Cell

class CtrlGrpPlugin(object):
    """Tracks the composition of the Replay's Players Control Groups.

    Using this plug-in, the Replay object will include the `ctrl_grp_trk`
    attribute. This attribute will store a dictionary of the control group
    compositions using the replay's human players' ids (`pid`) as keys.
    i.e.:
	
	    `dict[pid (int):  control_group_compositions (dict)]`

    Each of these dictionaries uses the `second` attribute of a
    `ControlGroupEvent` as an index and organises the control group
    composition as one more dictionary, indexed with the integers 1 to 9,
    which stores a list of units that compose each one of the nine control
    groups of the player. i.e.

        `dict[pid(int): dict[second(int): dict[group(int): list_of_units]]]`
    """
    from sc2reader.engine.plugins import SelectionTracker
    sc2reader.engine.register_plugin(SelectionTracker())
    name = "CtrlGrpPlugin"

    def handleInitGame(self, event, replay):
        replay.ctrl_grp_trk = dict()
        for human in replay.humans:
            selection = human.selection
            replay.ctrl_grp_trk[human.pid] = {0:{k: v for k, v
                                                in selection.items()
                                                if 0<k<10}}

    def handleEvent(self, event, replay):

        if isinstance(event, sc2reader.events.game.ControlGroupEvent):
            selection = event.player.selection
            replay.ctrl_grp_trk[event.player.pid][event.second] = {
                                                        k: v for k, v
                                                        in selection.items()
                                                        if 0<k<10}

sc2reader.engine.register_plugin(CtrlGrpPlugin())